/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class signUpMenu extends javax.swing.JFrame {

    /**
     * Creates new form signUpMenu
     */
    public signUpMenu() {
        initComponents();
    }
    
    public static boolean signUpUser(String email, String profileName, String password) {
        String query = "INSERT INTO user (email, profileName, password) VALUES (?, ?, ?)";
        try (Connection con = sqlConnection.getConnection(); 
            PreparedStatement pst = con.prepareStatement(query)) {
            pst.setString(1, email);
            pst.setString(2, profileName);
            pst.setString(3, password);
            int result = pst.executeUpdate();
            return result > 0;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orangeBar = new javax.swing.JPanel();
        whiteBar = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();
        jEmailField = new javax.swing.JTextField();
        jProfileNameField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        clickSignUpButton = new javax.swing.JButton();
        returnBackSUButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orangeBar.setBackground(new java.awt.Color(255, 51, 0));

        whiteBar.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\aemre\\OneDrive\\Documents\\NetBeansProjects\\C#\\src\\images\\orange-logo.png"));
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout whiteBarLayout = new javax.swing.GroupLayout(whiteBar);
        whiteBar.setLayout(whiteBarLayout);
        whiteBarLayout.setHorizontalGroup(
            whiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whiteBarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        whiteBarLayout.setVerticalGroup(
            whiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whiteBarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signUpLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLabel.setText("Sign Up");

        jEmailField.setBackground(new java.awt.Color(255, 255, 255));
        jEmailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmailField.setForeground(new java.awt.Color(0, 0, 0));
        jEmailField.setText("yourname@tedu.edu.tr(Only tedu mails)");
        jEmailField.setBorder(null);
        jEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailFieldActionPerformed(evt);
            }
        });

        jProfileNameField.setBackground(new java.awt.Color(255, 255, 255));
        jProfileNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jProfileNameField.setForeground(new java.awt.Color(0, 0, 0));
        jProfileNameField.setText("profileName");
        jProfileNameField.setBorder(null);
        jProfileNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProfileNameFieldActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        clickSignUpButton.setBackground(new java.awt.Color(255, 51, 0));
        clickSignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clickSignUpButton.setText("Click to Sign Up");
        clickSignUpButton.setBorder(null);
        clickSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickSignUpButtonActionPerformed(evt);
            }
        });

        returnBackSUButton.setBackground(new java.awt.Color(255, 51, 0));
        returnBackSUButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        returnBackSUButton.setText("Return Back");
        returnBackSUButton.setBorder(null);
        returnBackSUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBackSUButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orangeBarLayout = new javax.swing.GroupLayout(orangeBar);
        orangeBar.setLayout(orangeBarLayout);
        orangeBarLayout.setHorizontalGroup(
            orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeBarLayout.createSequentialGroup()
                .addComponent(whiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(536, 536, 536)
                .addGroup(orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orangeBarLayout.createSequentialGroup()
                        .addComponent(signUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(orangeBarLayout.createSequentialGroup()
                        .addGroup(orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clickSignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jEmailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                                .addComponent(jProfileNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                            .addComponent(returnBackSUButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        orangeBarLayout.setVerticalGroup(
            orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeBarLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jProfileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clickSignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnBackSUButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
            .addComponent(whiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orangeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orangeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailFieldActionPerformed

    private void jProfileNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProfileNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProfileNameFieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void returnBackSUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBackSUButtonActionPerformed
        new loginMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnBackSUButtonActionPerformed

    private void clickSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickSignUpButtonActionPerformed
        String profileName = jProfileNameField.getText();
        String email = jEmailField.getText();
        String password = new String(jPasswordField1.getPassword());

        if (signUpUser(email, profileName, password))
        {
            JOptionPane.showMessageDialog(this, "Sign Up Successful!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sign Up Failed. Try again.");
        }
    }//GEN-LAST:event_clickSignUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clickSignUpButton;
    private javax.swing.JTextField jEmailField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jProfileNameField;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel orangeBar;
    private javax.swing.JButton returnBackSUButton;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JPanel whiteBar;
    // End of variables declaration//GEN-END:variables
}
